#services:
#  nginx:
#    image: nginx_deb
#    ports:
#        - '80:80'
#    volumes:
#        - ./nginx:/etc/nginx/conf.d
#        - ./logs/nginx:/var/log/nginx
#        - ./wordpress:/var/www/html
#    links:
#        - wordpress
#    restart: always
#  mysql:
#    image: mariadb
#    ports:
#        - '3306:3306'
#    volumes:
#        - ./db-data:/var/lib/mysql
#    environment:
#        - MYSQL_ROOT_PASSWORD=Strong password
#    restart: always
#  
#  wordpress:
#    image: wordpress_deb
#    ports:
#        - '9000:9000'
#    volumes:
#        - ./wordpress:/var/www/html
#    environment:
#        - WORDPRESS_DB_NAME=wpdb
#        - WORDPRESS_TABLE_PREFIX=wp_
#        - WORDPRESS_DB_HOST=mysql
#        - WORDPRESS_DB_PASSWORD=Strong password
#    links:
#        - mysql
#    restart: always

#services:
#  web:
#    image: nginx_deb
#    ports:
#      - '8080:80'
#    volumes:
#      - ./src:/var/www/html/
#      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
#    links:
#      - php-fpm
#  php-fpm:
#    ports:
#      - "9000:9000"
#    image: wordpress_deb
#    volumes:
#      - ./src/index.php:/var/www/html/index.php
#      - ./fpm_conf:/etc/php/7.3/fpm/
services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html
