#services:
#  web:
#    image: nginx:latest
#    ports:
#      - '8080:80'
#    volumes:
#      - wordpress-files:/var/www/html
#      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
#    links:
#      - php-fpm
#  php-fpm:
#    ports:
#     - "9000:9000"
#    image: word
#    volumes:
#      - ./fpm_conf/:/etc/php/7.3/fpm/
#      - wordpress-files:/var/www/html
#volumes:
#  wordpress-files:
#    external: true


services:
  nginx:
    #context: ./requirements/nginx/
    build: ./requirements/nginx/
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - wordpress:/var/www/html
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
     - docker-network
  mysql:
    image: mariadb:latest
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    networks:
     - docker-network
  wordpress:
    #context: ./requirements/wordpress/
    image: wordpress
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - docker-network
    restart: always

networks:
  docker-network:

volumes:
  wordpress:
    external: true
  mysql:
    external: true
