services:
  nginx:
    build: requirements/nginx/
    ports:
      - '443:443'
    volumes:
      - wordpress:/var/www/html
      - requirements/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-network
    restart: always
  mysql:
    # build: requirements/mysql/
    networks:
      - docker-network
    image: mariadb:latest
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - .env
    restart: always
  php-fpm:
    depends_on:
    - mysql
    build: requirements/wordpress/
    volumes:
      - wordpress:/var/www/html
      - requirements/wordpress/fpm_conf:/etc/php/7.3/fpm
    env_file:
      - .env
    networks:
      - docker-network
    restart: always

networks:
  docker-network:

volumes:
  wordpress:
    external: true
  mysql:
    external: true

#curl --data "user_name=USERNAMEHERE&admin_password=PasswordHere&admin_password2=PasswordHere&admin_email=username@email.addr&blog_public=checked&Submit=submit" "http://site.name/wp-admin/install.php?step=2